# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/blog',
                'doc_host': 'https://avivleemann.github.io',
                'git_url': 'https://github.com/avivleemann/blog',
                'lib_path': 'blog'},
  'syms': {'blog.core': {'blog.core.foo': ('core.html#foo', 'blog/core.py')}}}
